=== tutors-sdk/tutors-mono-repo/tests/contract/messages/versions/lo-event.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "courseId": {
      "type": "string"
    },
    "courseUrl": {
      "type": "string"
    },
    "img": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "courseTitle": {
      "type": "string"
    },
    "loRoute": {
      "type": "string"
    },
    "user": {
      "type": "object",
      "properties": {
        "fullName": {
          "type": "string"
        },
        "avatar": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "sentiment": {
          "type": "string"
        }
      },
      "required": [
        "fullName",
        "avatar",
        "id"
      ],
      "additionalProperties": false
    },
    "type": {
      "type": "string"
    },
    "isPrivate": {
      "type": "boolean"
    },
    "icon": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "required": [
    "courseId",
    "courseUrl",
    "title",
    "courseTitle",
    "loRoute",
    "user",
    "type",
    "isPrivate"
  ],
  "additionalProperties": false
}

=== tutors-sdk/tutors-mono-repo/tests/contract/messages/recorded/lo-event.v1.json
{
  "courseId": "contract-course",
  "courseUrl": "contract-course.netlify.app",
  "img": "https://contract-course.netlify.app/topic-0/lab-0/lab-0.png",
  "title": "Lab 1",
  "courseTitle": "Course contract-course",
  "loRoute": "/lab/contract-course/topic-0/lab-0",
  "user": {
    "fullName": "Ann",
    "avatar": "https://avatars.example/ann.png",
    "id": "ann",
    "sentiment": "neutral"
  },
  "type": "lab",
  "isPrivate": false
}
